#spring.application.name=ITPJan2026Springboot
#spring.profiles.active=local
#server.port=8085
# PostgreSQL Database Configuration
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://localhost:5432/itpjan2026springbootdb
#spring.datasource.username=postgres
#spring.datasource.password=Wipro@123
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.hibernate.ddl-auto=update
#spring.security.user.name=tom
#spring.security.user.password=jerry

#JWT Secret Key
jwt.secret=pooja123_pranav987_pratik568_sanskar765_itpreneurpune_fullstack_development

#MySQL 
#server.port=8085
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/itpjan2026springbootdb
#spring.datasource.username=root
#spring.datasource.password=
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.hibernate.ddl-auto=create


#spring.application.name=ITPJan2026Springboot
#server.port=8085

